# Start from the official Playwright image which already includes browsers and dependencies
FROM mcr.microsoft.com/playwright:v1.53.0-jammy

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app
COPY . .
COPY .env.prod .env
RUN yarn
RUN yarn build-only
# RUN yarn --production


# Set up display for headed mode
ENV DISPLAY=:99

# Create a startup script
RUN echo '#!/bin/bash\n\
# Unlock previous XServer
rm -f /tmp/.X99-lock\n\
\n\
# Start Xvfb\n\
Xvfb :99 -screen 0 1280x720x24 -ac &\n\
\n\
# Start a window manager\n\
if command -v fluxbox &> /dev/null; then\n\
  fluxbox &\n\
elif command -v openbox &> /dev/null; then\n\
  openbox &\n\
fi\n\
\n\
# Change to app directory and start the server\n\
cd /app\n\
cd prisma && npx prisma generate\n\
cd ..\n\
yarn server:dev # will optimize prod server later\n\
' > /usr/local/bin/start-prod.sh && chmod +x /usr/local/bin/start-prod.sh

# Command to start the production server
CMD ["/usr/local/bin/start-prod.sh"]
