services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server.prod
    image: delfi-server
    labels:
      - "com.docker.compose.project=delfi-web"
    container_name: delfi-server
    restart: on-failure:max=2
    ports:
      - 3011:5000
    depends_on:
      - db
    links:
      - db

  db:
    image: delfi-db:latest
    container_name: delfi-db
    restart: on-failure:max=2
    build:
      context: .
      dockerfile: ./Dockerfile.db
    labels:
      - "com.docker.compose.project=delfi-web"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=delfi
    ports:
      - 3012:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  backup:
    image: delfi-backup:latest
    container_name: delfi-backup
    restart: on-failure:max=2
    build:
      context: .
      dockerfile: ./Dockerfile.backup
    labels:
      - "com.docker.compose.project=delfi-web"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=delfi
    volumes:
      - /Users/Arthur/code/delfi-web/backups:/backup-dir
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
    name: delfi-data