services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server.dev
    labels:
      - "com.docker.compose.project=delfi-web"
    container_name: delfi-server
    restart: on-failure:max=2
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      # Mount the source code for live reload
      - ./:/app
      - /app/node_modules
      # Exclude certain directories from the volume to prevent container issues
      - /app/chrome-data
      - /app/dist
    environment:
      - NODE_ENV=development
    
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend.dev
    container_name: delfi-frontend-dev
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      # Mount the source code for live reload
      - ./:/app
      - /app/node_modules
      - /app/chrome-data
    environment:
      - NODE_ENV=development
    
  db:
    image: delfi-db:latest
    container_name: delfi-db-dev
    build:
      context: .
      dockerfile: ./Dockerfile.db
    labels:
      - "com.docker.compose.project=delfi-web"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=delfi
    ports:
      - 3002:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: delfi-data