export enum MONTHS {"JAN"=0,"FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"};

export const colors = {
	gray1: "#F8F9FA",
	gray2: "#F4F5F6",
	gray3: "#F0F1F2",
	gray4: "#E1E3E5",
	gray5: "#D8DADE",
	gray6: "#C0C3C8",
	gray7: "#ACB0B6",
	gray8: "#90959B",
	gray9: "#798087",
	gray10: "#565F66",
	gray11: "#363F44",
	gray12: "#1F2528",
	gray13: "#101516",

	seafoam1: "#e3fafe",
	seafoam2: "#c5f4fd",
	seafoam3: "#a5eefc",
	seafoam4: "#81e8fb",
	seafoam5: "#53e1f9",
	seafoam6: "#3cb0c4",
	seafoam7: "#10798b",
	seafoam8: "#03414c",

	// purple1: "#f3deff",
	// purple2: "#e6bdff",
	// purple3: "#d99aff",
	// purple4: "#cc75fe",
	// purple5: "#be47fb",
	// purple6: "#8c32ba",
	// purple7: "#5e1f7e",
	// purple8: "#330d46",

	green1: "#e0f6e8",
	green2: "#c0ecd1",
	green3: "#9ee2ba",
	green4: "#79d8a3",
	green5: "#4ccd8d",
	green6: "#369867",
	green7: "#226644",
	green8: "#0f3823",

	red1: "#fad7da",
	red2: "#f1b0b6",
	red3: "#e68793",
	red4: "#d85d71",
	red5: "#c72850",
	red6: "#931b39",
	red7: "#620f24",
	red8: "#360410",

	cherry1: "rgb(255, 84, 84)",
	cherry2: "rgb(246, 40, 40)",
	cherry3: "rgb(219, 9, 9)",
	apple1: "rgb(214, 53, 53)",
	apple2: "rgb(177, 28, 28)",
	apple3: "rgb(156, 13, 13)",
	chocolate1: "#a1572c",
	chocolate2: "#8a431a",
	chocolate3: "#73310b",
	orange1: "rgb(255, 147, 63)",
	orange2: "rgb(235, 119, 29)",
	orange3: "rgb(222, 101, 7)",
	peach1: "#fb9467",
	peach2: "#fa8653",
	peach3: "#f37842",
	yellow1: "#ffcf3f",
	yellow2: "#f8c220",
	yellow3: "#ecb209",
	lime1: "#92d72d",
	lime2: "#81c61d",
	lime3: "#6aae09",
	forest1: "#4f9c25",
	forest2: "#3b8116",
	forest3: "#2d7108",
	teal1: "#27d7cf",
	teal2: "#06c6bd",
	teal3: "#00afa7",
	sky1: "#7dd0ff",
	sky2: "#4fbdfb",
	sky3: "#33abee",
	blue1: "#2591e6",
	blue2: "#107dd2",
	blue3: "#006abc",
	navy1: "#23508f",
	navy2: "#194481",
	navy3: "#0e356d",
	lavender1: "#9a7fec",
	lavender2: "#8f72e6",
	lavender3: "#8263de",
	violet1: "#8046fb",
	violet2: "#7031f5",
	violet3: "#6122e8",
	purple1: "#b728c5",
	purple2: "#9e17ab",
	purple3: "#900d9d",
	blush1: "#ff89bb",
	blush2: "rgb(244, 109, 166)",
	blush3: "rgb(234, 84, 148)",
	magenta1: "#ee37c8",
	magenta2: "#d515ad",
	magenta3: "#c1099b",
}


const IconSources = [
	'material-symbols',
] as const;
export type IconSource = typeof IconSources[number];

export enum TagColor {
	cherry1 = 'cherry1',
	cherry2 = 'cherry2',
	cherry3 = 'cherry3',
	apple1 = 'apple1',
	apple2 = 'apple2',
	apple3 = 'apple3',
	chocolate1 = 'chocolate1',
	chocolate2 = 'chocolate2',
	chocolate3 = 'chocolate3',
	orange1 = 'orange1',
	orange2 = 'orange2',
	orange3 = 'orange3',
	peach1 = 'peach1',
	peach2 = 'peach2',
	peach3 = 'peach3',
	yellow1 = 'yellow1',
	yellow2 = 'yellow2',
	yellow3 = 'yellow3',
	lime1 = 'lime1',
	lime2 = 'lime2',
	lime3 = 'lime3',
	forest1 = 'forest1',
	forest2 = 'forest2',
	forest3 = 'forest3',
	teal1 = 'teal1',
	teal2 = 'teal2',
	teal3 = 'teal3',
	sky1 = 'sky1',
	sky2 = 'sky2',
	sky3 = 'sky3',
	blue1 = 'blue1',
	blue2 = 'blue2',
	blue3 = 'blue3',
	navy1 = 'navy1',
	navy2 = 'navy2',
	navy3 = 'navy3',
	lavender1 = 'lavender1',
	lavender2 = 'lavender2',
	lavender3 = 'lavender3',
	violet1 = 'violet1',
	violet2 = 'violet2',
	violet3 = 'violet3',
	purple1 = 'purple1',
	purple2 = 'purple2',
	purple3 = 'purple3',
	blush1 = 'blush1',
	blush2 = 'blush2',
	blush3 = 'blush3',
	magenta1 = 'magenta1',
	magenta2 = 'magenta2',
	magenta3 = 'magenta3',
}

export type Icon = {
	name: string,
	source: IconSource,
	source_id: string,
	style?: { [key: string]: string | number }
}

export const Icons = {
	"bank": {
		name: "bank",
		source: "material-symbols",
		source_id: "account_balance",
	},
	"briefcase": {
		name: "briefcase",
		source: "material-symbols",
		source_id: "work",
	},
	"car": {
		name: "car",
		source: "material-symbols",
		source_id: "directions_car",
	},
	"category": {
		name: "category",
		source: "material-symbols",
		source_id: "category",
		style: {
			translate: '0 -6%',
		}
	},
	"chart-line": {
		name: "chart-line",
		source: "material-symbols",
		source_id: "monitoring",
	},
	"checklist": {
		name: "checklist",
		source: "material-symbols",
		source_id: "checklist",
	},
	"child": {
		name: "child",
		source: "material-symbols",
		source_id: "child_care",
	},
	"church": {
		name: "church",
		source: "material-symbols",
		source_id: "church",
	},
	"cake": {
		name: "cake",
		source: "material-symbols",
		source_id: "cake",
	},
	"compass": {
		name: "compass",
		source: "material-symbols",
		source_id: "explore",
	},
	"commute": {
		name: "commute",
		source: "material-symbols",
		source_id: "commute",
	},

	"dollar-bills": {
		name: "dollar-bills",
		source: "material-symbols",
		source_id: "payments",
	},
	"fast-food": {
		name: "fast-food",
		source: "material-symbols",
		source_id: "fastfood",
	},
	"faucet": {
		name: "faucet",
		source: "material-symbols",
		source_id: "faucet",
	},
	"fuel": {
		name: "fuel",
		source: "material-symbols",
		source_id: "local_gas_station",
	},
	"gavel": {
		name: "gavel",
		source: "material-symbols",
		source_id: "gavel",
	},
	"gift": {
		name: "gift",
		source: "material-symbols",
		source_id: "featured_seasonal_and_gifts",
	},
	"give-heart": {
		name: "give-heart",
		source: "material-symbols",
		source_id: "volunteer_activism",
	},
	"graduation-cap": {
		name: "graduation-cap",
		source: "material-symbols",
		source_id: "school",
	},
	"grocery": {
		name: "grocery",
		source: "material-symbols",
		source_id: "grocery",
	},
	"hanger": {
		name: "hanger",
		source: "material-symbols",
		source_id: "checkroom",
	},
	"heartbeat": {
		name: "heartbeat",
		source: "material-symbols",
		source_id: "cardiology",
	},
	"home": {
		name: "home",
		source: "material-symbols",
		source_id: "cottage",
	},
	"ice-cream": {
		name: "ice-cream",
		source: "material-symbols",
		source_id: "icecream",
	},
	"lightbulb": {
		name: "lightbulb",
		source: "material-symbols",
		source_id: "lightbulb",
	},
	"money-bag": {
		name: "money-bag",
		source: "material-symbols",
		source_id: "money_bag",
	},
	"paw": {
		name: "paw",
		source: "material-symbols",
		source_id: "pets",
	},
	"parking-sign": {
		name: "parking-sign",
		source: "material-symbols",
		source_id: "parking_sign",
	},
	"party-popper": {
		name: "party-popper",
		source: "material-symbols",
		source_id: "celebration",
	},
	"piggy-bank": {
		name: "piggy-bank",
		source: "material-symbols",
		source_id: "savings",
	},
	"question-circle": {
		name: "question-circle",
		source: "material-symbols",
		source_id: "help",
	},
	"self-care": {
		name: "self-care",
		source: "material-symbols",
		source_id: "self_care",
		style: {
			translate: '0 -6%',
		}
	},
	"shopping-cart": {
		name: "shopping-cart",
		source: "material-symbols",
		source_id: "shopping_cart",
	},
	"shirt": {
		name: "shirt",
		source: "material-symbols",
		source_id: "apparel",
	},
	"smiley": {
		name: "smiley",
		source: "material-symbols",
		source_id: "sentiment_excited",
	},
	// "toothbrush": {
	// 	name: "toothbrush",
	// 	source: "material-symbols",
	// 	source_id: "",
	// },
	"tag": {
		name: "tag",
		source: "material-symbols",
		source_id: "sell",
	},
	"tooth": {
		name: "tooth",
		source: "material-symbols",
		source_id: "dentistry",
	},
	"transfer": {
		name: "transfer",
		source: "material-symbols",
		source_id: "swap_horiz",
	},
	"utensils": {
		name: "utensils",
		source: "material-symbols",
		source_id: "local_dining",
	},
	"wallet": {
		name: "wallet",
		source: "material-symbols",
		source_id: "account_balance_wallet",
	},
} as const;

export type IconName = keyof typeof Icons;
export type IconIdentifier = IconName | `${IconSource}::${string}`; // Allow custom icons in the format source::source_id